apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cwlogs-alert.fullname" . }}
  namespace: {{ template "cwlogs-alert.namespace" . }}
  labels:
    {{- include "cwlogs-alert.labels" . | nindent 4 }}
type: Opaque
data:
  ldap-toml: {{ .Values.config-toml | b64enc | quote }}
